color-scheme: Log errors at stderr+rename title

diff --git a/bin/color-scheme b/bin/color-scheme
--- a/bin/color-scheme
+++ b/bin/color-scheme
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 current=$(gsettings get org.gnome.desktop.interface color-scheme)
-if [ $? -ne 0 ]; then echo "Could not fetch current color-scheme"; exit 1; fi
+if [ $? -ne 0 ]; then echo "Could not fetch current color-scheme" >&2; exit 1; fi
 echo "Current color-scheme: $current"
 
 current_is_default="FALSE"
@@ -12,12 +12,12 @@ case "$current" in
 	"'prefer-light'") current_is_light="TRUE" ;;
 	"'default'") current_is_default="TRUE" ;;
 esac
-new_color_scheme=$(zenity --list --title "Color scheme" --column= --column="Theme" --radiolist $current_is_default default $current_is_light prefer-light $current_is_dark prefer-dark)
-if [ $? -ne 0 ]; then echo "Could not get new mode from zenity"; exit 1; fi
+new_color_scheme=$(zenity --list --title "Color scheme" --column= --column="Color scheme" --radiolist $current_is_default default $current_is_light prefer-light $current_is_dark prefer-dark)
+if [ $? -ne 0 ]; then echo "Could not get new mode from zenity" >&2; exit 1; fi
 
 echo "New color-scheme: $new_color_scheme"
 
 if ! $(gsettings set org.gnome.desktop.interface color-scheme "$new_color_scheme"); then
-	echo "Could not set new color-scheme"
+	echo "Could not set new color-scheme" >&2
 	exit 1
 fi
